### ISSUE TITLE
Screenshot and crop our sites

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/buildicus-op1#1]
Go through all our client sites and screenshot the best looking parts (i trust your judgement). 

Then crop those screenshots to 768 x 512 px and upload them to the 'general-assets' folder in our buildicus google drive. 

due:
8-19-15    11p
[gu-actual=0]

**Comment by AaronAguilar** [comment]
Take about 2-4  screenshots per site? Or just one?

**Comment by rodneystrong** [comment]
2-3 sounds good.

**Comment by rcsargent** [comment]
Eh ? :) http://codepen.io/rcsctr/pen/NPxPvE

**Comment by AaronAguilar** [comment]
Just live sites or can I also do recent ones that are hosted on github ?

**Comment by rodneystrong** [comment]
In case you didn't get my text: 
No, not just the live sites. Use the ones that are on gh-pages also please. thanks

**Comment by AaronAguilar** [comment]
Got: Caruthers, Face and Skin, HPC, Knot away, La vogue, northpointe,  One woman adventure, Pumpkin, Solista, Sublime, TaKo, and UCP
Upload! 
https://drive.google.com/folderview?id=0BzVFl2mibGTnflBHdmJ2R1RPNUh1Ymp5WjdWZEo3dURuUHNjZWlnZjlncFZBVHB5bkpaMU0&usp=sharing

**Comment by irms** [comment]
Update?

**Comment by AaronAguilar** [comment]
Will do!
From my understanding: HPC has gone live. 
Others: Cenpa, Wisescuba, Codegirls, Screamer, Huntress?
GB Aqua, Melissa Locations, and Dixon are in construction, correct?

**Comment by irms** [comment]
Closing. Concierge is moving to editllc.com.
