### ISSUE TITLE
Concierge - Footer

### ISSUE THREAD

**Issue by irms** [EditLLC/buildicus-op1#11]
The footer appears to end the page abruptly.

<img width="1438" alt="screenshot 2015-10-04 17 38 00" src="https://cloud.githubusercontent.com/assets/643997/10271260/b3d2382c-6abe-11e5-9022-f0547bb7e39e.png">

Let's try a larger footer a la most modern websites. Example:

<img width="1284" alt="screenshot 2015-10-04 17 40 29" src="https://cloud.githubusercontent.com/assets/643997/10271269/0b938534-6abf-11e5-989b-09435171af1e.png">
[gu-actual=0]

**Comment by irms** [comment]
*nudge*

**Comment by rodneystrong** [comment]
on it

**Comment by rodneystrong** [comment]
cool if I just copy the buildicus.com footer?

**Comment by irms** [comment]
if you don't have a vision for something else, sure.

**Comment by irms** [comment]
Closing. Concierge is moving to editllc.com.
