### ISSUE TITLE
Concierge - Responsiveness

### ISSUE THREAD

**Issue by irms** [EditLLC/buildicus-op1#16]
There are many problems with the responsive ness. Rather than list them all, let's just make it happen. I'm happy to double check the work when it's complete.
[gu-actual=0]

**Comment by rodneystrong** [comment]
this is drivin me nuts.. if i can't get this by tomorrow i'm gonna need a fresh set of eyes.

**Comment by irms** [comment]
*nudge*

**Comment by irms** [comment]
Moving to EditLLC.com. Closing.
