### ISSUE TITLE
Homepage - Move Log In to Top

### ISSUE THREAD

**Issue by irms** [EditLLC/buildicus-op1#17]
I keep looking for the login button at the top. It is standard to have a login/sign up button at top, so let's do it. 

Add a thin bar at the very top _above_ "id=intro"

Something like:

```
<div style="background-color: #00AEEF; height:25px;border-bottom:1px solid #aaa; color: #fff; text-align:right;">hi</div>
```

but nicer ;)

And remove the login nav link from the existing bar.

**Comment by rodneystrong** [comment]
Ah, this is for the buildicus.com home page. 

Can do.

**Comment by irms** [comment]
*nudge*

**Comment by irms** [comment]
Assigning to myself.
