### ISSUE TITLE
Brand the Modal and Make Less...Bootstrappy

### ISSUE THREAD

**Issue by irms** [EditLLC/buildicus-op1#18]
Buildicus version:

https://www.dropbox.com/s/pbns014krlvtkkq/Screenshot%202015-10-05%2022.31.16.png?dl=0

Wix version:

https://www.dropbox.com/s/xpnrmfd7sej8mvq/Screenshot%202015-10-05%2022.31.58.png?dl=0

Weebly version:

https://www.dropbox.com/s/euwxn0kro3wev4b/Screenshot%202015-10-05%2022.32.21.png?dl=0

This was a great first run, but it's time to punch it up a bit :)

More color, more branding, less bootstrap default?
[gu-actual=0]

**Comment by rodneystrong** [comment]
Do we support a "login with google or facebook" option? If so I've got a good concept in mind.

**Comment by irms** [comment]
We do not.

**Comment by irms** [comment]
*nudge*

**Comment by rodneystrong** [comment]
On it. Personal due date: 
11-13-15  4pm
