### ISSUE TITLE
Fix Lorem Ipsum content

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/buildicus-op1#2]
Go to this page: http://buildicus.com/concierge/

The section about "our customers love us" has lorem ipsum text.

Go to this url and crop her face: http://www.yelp.com/biz_photos/knot-away-therapy-fresno?select=ATJjhU5sCPa57m09sgf1ug

I'll get you text to use. *UPDATE* got the text! 
"My website is now a sophisticated and professional website. It is all I ever imagined and dreamed it could be thanks to Alex and Richard. True visionaries, new friends, along with one extremely proud and very happy client." -Linda Sepulveda, LMT. Knot Away Therapy

Another face to crop out: http://www.ulfusa.com/publishImages/about~~element13.jpg

text: "I still love love my site :)"

due:
9-18-15   4p

updated due date:
9-28-15  12p

**Comment by rodneystrong** [comment]
Oh yea, forgot to mention, please update this on gh-pages.

**Comment by rodneystrong** [comment]
@purplyrocky wow.. you failed on this  T_T)  

Please get this done by the updated due date.

**Comment by purplyrocky** [comment]
Yeah that's what i was trying to explain to you today, i accidentally update this on the concierge page repo, i'll fix this tonight

**Comment by rodneystrong** [comment]
Unfortunately the changes you made still aren't showing up on buildicus.com/concierge  :'( 

Did you double-check the site after you pushed? http://buildicus.com/concierge/

**Comment by purplyrocky** [comment]
Yes, I pushed to this repo 
http://editllc.github.io/buildicus-op1/concierge/concierge.html

**Comment by rodneystrong** [comment]
oOOOOoh I see what happened. 

Could you make the changes you made to the concierge.html page to the index.html page instead that's in that same folder please? 

Reason is because we link to the index.html page and not the concierge.html page from the buildicus.com home page.

**Comment by purplyrocky** [comment]
Done

**Comment by rodneystrong** [comment]
thaaaank you ma'am!
