### ISSUE TITLE
Remove Period from Zach's Picture

### ISSUE THREAD

**Issue by irms** [EditLLC/buildicus-op1#21]
Just a stray

<img width="274" alt="screenshot 2015-10-05 22 45 34" src="https://cloud.githubusercontent.com/assets/643997/10301017/df2504b0-6bb2-11e5-9413-f801ec4c7ff1.png">

**Comment by rodneystrong** [comment]
I know it's still a little early, but should I just remove @zackify ? Maybe let the door hit him on the way out? ;D

**Comment by jonadesign** [comment]
lol... awww

**Comment by zackify** [comment]
I think I deserve two years on the site since I wasn't on there for the
first year and a half

**Comment by rodneystrong** [comment]
actually you weren't on there for the first year and 9 months  :-\  #wasntuptome

**Comment by jonadesign** [comment]
done.
