### ISSUE TITLE
Buildicus Marketing Page

### ISSUE THREAD

**Issue by jonadesign** [EditLLC/buildicus-op1#22]
The marketing page only has information on what we offer. We don't have an example of what the generator does. 

Suggestion: 
- add a row that will tie into the page and implement a layout that will showcase the product
- screen shots of how the user can change the images & content

**Comment by rodneystrong** [comment]
@jonadesign  You got the layout/screenshots I can put into this section?  If so, please upload them to this issue and I will implement.

**Comment by jonadesign** [comment]
@irms for this section --> did you want a comparison between concierge & generator? I know you had mentioned something like this is what concierge offers.....and this is generator

**Comment by irms** [comment]
@jonafied yes. A comparison between generator and DIY.

**Comment by rodneystrong** [comment]
@jonadesign  it's possible @irms is referring to a comparison between our generator and the DIY solutions out there like weebly + squarespace.

**Comment by jonadesign** [comment]
something like this, to add into the marketing page --> 

[generator.pdf](https://github.com/EditLLC/buildicus-op1/files/12075/generator.pdf)

**Comment by irms** [comment]
yes.

**Comment by jonadesign** [comment]
@irms : any suggestions on content?

**Comment by irms** [comment]
I actually like what you have, except instead of "content" I would call it
"text"

And for the headline it could be simply, "Just two steps to finish your
website."

**Comment by jonadesign** [comment]
word!

**Comment by jonadesign** [comment]
@irms : did you want me to incorporate this or pass off the psds?

**Comment by irms** [comment]
@jonafied if you've got time, I say go for it.
