### ISSUE TITLE
Remove Kitten from Blog Logo

### ISSUE THREAD

**Issue by irms** [EditLLC/buildicus-op1#25]
That was something Nick added in as a placeholder, but we just don't need it at all.

<img width="441" alt="screenshot 2015-10-05 22 55 43" src="https://cloud.githubusercontent.com/assets/643997/10301135/465f8f82-6bb4-11e5-8c89-b2119bc9e7d1.png">

**Comment by rodneystrong** [comment]
Ah yes, good ol' kitty.

**Comment by irms** [comment]
*nudge*

**Comment by rodneystrong** [comment]
poor kitty. removed. done. 

should we eventually replace it with your headshot?
