### ISSUE TITLE
Users Clicking on the Icons

### ISSUE THREAD

**Issue by jonadesign** [EditLLC/buildicus-op1#27]
The users are clicking on these icons, hoping it will take them to an additional page.
Suggestion :
- maybe reverse the color of the icons & the headings
- greying out the icons will allow the users to think it's disabled
- or ? any feedback is valuable, as well

<img width="1313" alt="screen shot 2015-10-07 at 2 48 38 pm" src="https://cloud.githubusercontent.com/assets/7379059/10352280/11a6d106-6d03-11e5-9e4d-9c7bb9a260f6.png">
<img width="1313" alt="screen shot 2015-10-07 at 2 48 55 pm" src="https://cloud.githubusercontent.com/assets/7379059/10352286/16286140-6d03-11e5-80f5-0b7a85ac160d.png">

**Comment by rodneystrong** [comment]
Actually, they have a really cool hover effect though, so i want to keep it. 

The real confusion I believe happens when the mouse cursors turns into a hand pointer; a universal indicator that it needs to be clicked. I'll change the CSS from cursor:pointer to cursor: default


Deal?
