### ISSUE TITLE
Make Buildicus.com SEO-Friendly  (Translated)

### ISSUE THREAD

**Issue by irms** [EditLLC/buildicus-op1#31]
See http://docs.transifex.com/live/seo/
[gu-actual=0]

**Comment by irms** [comment]
Moved to MediaTemple to get access to .htaccess. (Github Pages does not offer that access.)

Needed to config headers for prerender.io.

**Comment by rodneystrong** [comment]
I just read the top 2 paragraphs of that link. That was enlightening. Bummer about gh-pages.
