### ISSUE TITLE
Concierge - Our Process Section

### ISSUE THREAD

**Issue by jonadesign** [EditLLC/buildicus-op1#32]
There's a dotted line that shows up when you click on the numbers, and it also shows up when you click other links, as well. Not sure if it's intended to be there.

<img width="710" alt="screen shot 2015-10-28 at 3 14 47 pm" src="https://cloud.githubusercontent.com/assets/7379059/10805048/4077e23c-7d88-11e5-9aaf-47313e981f2c.png">

**Comment by rodneystrong** [comment]
seems to have been resolved. dont remember if it was me or you.
