### ISSUE TITLE
Login doesn't have an option for - Forget Password?

### ISSUE THREAD

**Issue by jonafied** [EditLLC/buildicus-op1#39]
I just noticed that there's no option for forget password --> any thoughts? 
It won't let me bypass this unless I type in my password
<img width="1236" alt="screen shot 2016-01-05 at 3 44 27 pm" src="https://cloud.githubusercontent.com/assets/7379059/12130945/7207569a-b3c3-11e5-983e-39b769d78020.png">

**Comment by rodneystrong** [comment]
I would say add a "Forgot password?" link right underneath the password field, the same way you have it setup in this screenshot: 

<img width="411" alt="screen shot 2016-01-05 at 3 51 02 pm" src="https://cloud.githubusercontent.com/assets/539962/12131052/32dccaa8-b3c4-11e5-917d-8c6d686be35d.png">


This is the link: http://generator.buildicus.com/auth/forgot-password

**Comment by jonafied** [comment]
looks like this -->
<img width="1234" alt="screen shot 2016-01-05 at 4 21 28 pm" src="https://cloud.githubusercontent.com/assets/7379059/12131557/66c077a8-b3c8-11e5-9e8a-bfb9e5b3d9ec.png">

**Comment by rodneystrong** [comment]
Props home girl.
