### ISSUE TITLE
Concierge - Our Latest Work - Lorem Ipsum

### ISSUE THREAD

**Issue by irms** [EditLLC/buildicus-op1#4]
On hover, each image shows lorem ipsum.

<img width="405" alt="screenshot 2015-10-04 17 28 19" src="https://cloud.githubusercontent.com/assets/643997/10271221/6f8fdcd8-6abd-11e5-9b28-20d9de089073.png">

due:
10-9-15   11p

**Comment by rodneystrong** [comment]
For the Title put the name of the site, for the Subtitle, put the URL of the site

**Comment by rodneystrong** [comment]
Also, have each project hyperlinked to the live site

**Comment by rodneystrong** [comment]
@purplyrocky do you think you'll be able to do this by 11p tonight? 

If not I'll take care of it. 

Sorry about the rush, but @rcsargent is getting anxious

**Comment by purplyrocky** [comment]
Yes, i can have it done by 11. Can you please update the due dates on the other issues you assigned to me? I noticed those were made days before I was assigned.

**Comment by rodneystrong** [comment]
please update them with due dates that you can handle

**Comment by purplyrocky** [comment]
Done. I just need the url for 
HPC, Inc and The Woodcraft

**Comment by rodneystrong** [comment]
For now, use the gh-pages URLs for those sites.

**Comment by rodneystrong** [comment]
Thanks for taking care of this. Real quick, could you also fix the "title" attributes on these as well? 

If you look at the screenshot in the description, you'll notice that the tooltip that pops up when you hover over the picture still states "project title 2 - lorem ipsum". 

Replace it with the same text you updated with.

**Comment by purplyrocky** [comment]
Done
