### ISSUE TITLE
Hero stock image too generic

### ISSUE THREAD

**Issue by jonafied** [EditLLC/buildicus-op1#40]
Feedback from the video teardown w/Steli & Hiten ::
- Choose an image that has the same vibe as the team
  - the team is very casual and laid back, the hero image would be ok if we gave off that same vibe

**Comment by jonafied** [comment]
I propose an image of our team in the header, any thoughts?

**Comment by irms** [comment]
What about this? With phone numbers blurred out and cropped appropriately?

![la-vogue-hi-res](https://cloud.githubusercontent.com/assets/643997/12190389/ed38a778-b57c-11e5-975e-0e94ad852ccb.jpg)

**Comment by jonafied** [comment]
Something like this might actually work. What website did you use to do this? @irms

**Comment by irms** [comment]
Placeit.net

**Comment by jonafied** [comment]
changed to --> 
<img width="1375" alt="screen shot 2016-01-11 at 1 16 15 pm" src="https://cloud.githubusercontent.com/assets/7379059/12246843/ab3ed860-b865-11e5-939e-51944f4008c3.png">
