### ISSUE TITLE
Header content 

### ISSUE THREAD

**Issue by jonafied** [EditLLC/buildicus-op1#41]
Feedback from the video teardown w/Steli & Hiten ::
- the content seems a bit too long
 - consider saying generate your mobile website in 5 minutes or less

**Comment by jonafied** [comment]
changed to -->
<img width="585" alt="screen shot 2016-01-07 at 3 18 25 pm" src="https://cloud.githubusercontent.com/assets/7379059/12185761/eea243f6-b551-11e5-9d2b-4dd97cde92b1.png">

**Comment by jonafied** [comment]
@irms : any thoughts on content? or is this ok?

**Comment by irms** [comment]
@jonafied that works for me!

**Comment by jonafied** [comment]
cool, done.
