### ISSUE TITLE
Header CTA button content

### ISSUE THREAD

**Issue by jonafied** [EditLLC/buildicus-op1#44]
Feedback from the video teardown w/Steli & Hiten ::
- the content doesn't match the header
 - consider changing the content to get my mobile website or generate your mobile website

**Comment by jonafied** [comment]
this -->
<img width="619" alt="screen shot 2016-01-07 at 3 20 55 pm" src="https://cloud.githubusercontent.com/assets/7379059/12185810/49a43642-b552-11e5-97c9-2510df3ed82e.png">
or -->
<img width="600" alt="screen shot 2016-01-07 at 3 21 53 pm" src="https://cloud.githubusercontent.com/assets/7379059/12185828/68da50d2-b552-11e5-8040-b48d875f12d1.png">

**Comment by irms** [comment]
The second one, please.

**Comment by jonafied** [comment]
done.
