### ISSUE TITLE
Header client support

### ISSUE THREAD

**Issue by jonafied** [EditLLC/buildicus-op1#45]
Feedback from the video teardown w/Steli & Hiten ::
- 3rd hierarchy - client support seems too enterprise and service
 - consider changing client support to call us or we'll help you, something to match the overall vibe of the website

**Comment by jonafied** [comment]
this -->
<img width="525" alt="screen shot 2016-01-07 at 3 23 19 pm" src="https://cloud.githubusercontent.com/assets/7379059/12185851/9f376e94-b552-11e5-8d4f-e5e7910f4abf.png">
or -->
<img width="574" alt="screen shot 2016-01-07 at 3 25 06 pm" src="https://cloud.githubusercontent.com/assets/7379059/12185880/dcdeccf6-b552-11e5-99e8-5ca8771faf2c.png">

or... any other suggestions?

**Comment by irms** [comment]
The second one, please. @jonafied

**Comment by jonafied** [comment]
done.
