### ISSUE TITLE
Concierge - Testimonials

### ISSUE THREAD

**Issue by irms** [EditLLC/buildicus-op1#7]
Second testimonial is dummy data still:

<img width="572" alt="screenshot 2015-10-04 17 32 41" src="https://cloud.githubusercontent.com/assets/643997/10271242/fb0d2464-6abd-11e5-8b98-83715e69fabc.png">

**Comment by rodneystrong** [comment]
fixed with https://github.com/EditLLC/buildicus-op1/commit/6979b8ff24277459f4d051213d4960128401c774

it was tiffany potter
