### ISSUE TITLE
Concierge - Contact Form Functionality

### ISSUE THREAD

**Issue by irms** [EditLLC/buildicus-op1#9]
I know this issue has been filed once before (by me), but it still isn't fixed. Contact form does not function, those leads should be pumped into Drip. 

Might I suggest removing the form altogether and use the Drip javascript instead.
[gu-actual=0]

**Comment by rodneystrong** [comment]
@irms or @rcsargent could one of you share the drip creds via lastpass with me please? thanks

**Comment by irms** [comment]
Invitations sent.

**Comment by irms** [comment]
*nudge*

**Comment by irms** [comment]
Closing. Concierge is moving to editllc.com.
